"""Device capability lists for the Nilan CTS602 driver, keyed by machine model."""

from typing import Dict, List


DEVICE_CAPABILITIES: Dict[int, List[str]] = {
    -1: [
        'target_temperature', 'measure_temperature',
        'target_temperature.water', 'measure_temperature.water',
        'target_temperature.ek',
        'nl_target_humidity',
        'fan_speed.inlet1', 'fan_speed.inlet2', 'fan_speed.inlet3', 'fan_speed.inlet4',
        'fan_speed.exhaust1', 'fan_speed.exhaust2', 'fan_speed.exhaust3', 'fan_speed.exhaust4',
        'fan_mode.ventilation',
        'pump_mode.run', 'pump_mode.mode', 'pump_mode.air_exchange', 'pump_mode.power_save',
        'insights_number.compressor_state', 'insights_number.hot_water_state',
        'insights_number.externalheater',
        'insights_number.waterpump_state', 'insights_number.defrosting_state',
        'insights_number.electricheater', 'insights_number.ventilation',
        'insights_number.run_state',
        'insights_dec_number.T0_controller', 'insights_dec_number.T1_intake',
        'insights_dec_number.T2_inlet', 'insights_dec_number.T3_exhaust',
        'insights_dec_number.T4_outlet', 'insights_dec_number.T5_cond',
        'insights_dec_number.T6_evap', 'insights_dec_number.T7_inlet',
        'insights_dec_number.T8_outdoor', 'insights_dec_number.T9_heater',
        'insights_dec_number.T10_extern',
        'insights_dec_number.T11_water_top', 'insights_dec_number.T12_water_bottom',
        'insights_dec_number.T13_return', 'insights_dec_number.T14_supply',
        'insights_dec_number.T15_room', 'insights_dec_number.T16_aux',
        'insights_dec_number.air_heater_capacity', 'insights_dec_number.central_heater_capacity',
        'insights_dec_number.compressor_capacity',
        'compressor_state',
        'electricheater',
        'externalheater',
        'hot_water_state',
        'waterpump_state',
        'defrosting_state',
        'measure_humidity',
        'measure_temperature.indoor', 'measure_temperature.outdoor',
        'measure_temperature.water_current',
        'measure_temperature.ek_supply', 'measure_temperature.ek_return',
        'measure_temperature.controller', 'measure_temperature.intake',
        'measure_temperature.inlet_before', 'measure_temperature.exhaust',
        'measure_temperature.outlet', 'measure_temperature.cond',
        'measure_temperature.evap', 'measure_temperature.inlet_after',
        'measure_temperature.heater', 'measure_temperature.extern',
        'measure_temperature.water_top', 'measure_temperature.water_bottom',
        'measure_temperature.panel', 'measure_temperature.aux', 'measure_co2',
        'fanstep_enum.ventilation', 'fanstep.inlet', 'fanstep.exhaust',
        'fanspeed.inlet', 'fanspeed.exhaust',
        'capacity.airheat', 'capacity.cenheat', 'capacity.compressor',
        'filter_days.left', 'filter_days.since',
        'run_state', 'heatpump_mode', 'heatpump_state', 'air_exchange_mode', 'power_save_mode',
        'cts602_type', 'heatpump_typecode',
        'hidden_string.version_major', 'hidden_string.version_minor',
        'hidden_string.version_release',
        'firmware_version', 'bus_version',
        'hidden_number.alarm_count', 'alarm_generic.filter', 'alarm_pump_device',
        'hidden_number.co2_enable',
    ],
    21: [
        'target_temperature', 'measure_temperature',
        'target_temperature.water', 'measure_temperature.water',
        'target_temperature.ek',
        'nl_target_humidity',
        'fan_speed.inlet1', 'fan_speed.inlet2', 'fan_speed.inlet3', 'fan_speed.inlet4',
        'fan_speed.exhaust1', 'fan_speed.exhaust2', 'fan_speed.exhaust3', 'fan_speed.exhaust4',
        'fan_mode.ventilation',
        'pump_mode.run', 'pump_mode.mode', 'pump_mode.air_exchange', 'pump_mode.power_save',
        'insights_number.compressor_state', 'insights_number.hot_water_state',
        'insights_number.waterpump_state', 'insights_number.defrosting_state',
        'insights_number.electricheater', 'insights_number.ventilation',
        'insights_number.run_state',
        'insights_dec_number.T0_controller', 'insights_dec_number.T1_intake',
        'insights_dec_number.T2_inlet',
        'insights_dec_number.T5_cond', 'insights_dec_number.T6_evap',
        'insights_dec_number.T7_inlet',
        'insights_dec_number.T8_outdoor', 'insights_dec_number.T10_extern',
        'insights_dec_number.T11_water_top', 'insights_dec_number.T12_water_bottom',
        'insights_dec_number.T13_return', 'insights_dec_number.T14_supply',
        'insights_dec_number.T15_room', 'insights_dec_number.T16_aux',
        'insights_dec_number.central_heater_capacity',
        'insights_dec_number.compressor_capacity',
        'compressor_state',
        'electricheater',
        'hot_water_state',
        'waterpump_state',
        'defrosting_state',
        'measure_humidity',
        'measure_temperature.indoor', 'measure_temperature.outdoor',
        'measure_temperature.water_current',
        'measure_temperature.ek_supply', 'measure_temperature.ek_return',
        'measure_temperature.controller', 'measure_temperature.intake',
        'measure_temperature.inlet_before',
        'measure_temperature.cond', 'measure_temperature.evap',
        'measure_temperature.inlet_after',
        'measure_temperature.extern', 'measure_temperature.water_top',
        'measure_temperature.water_bottom',
        'measure_temperature.panel', 'measure_co2',
        'fanstep_enum.ventilation', 'fanstep.inlet', 'fanspeed.inlet', 'fanspeed.exhaust',
        'capacity.cenheat', 'capacity.compressor',
        'filter_days.left', 'filter_days.since',
        'run_state', 'heatpump_mode', 'heatpump_state', 'air_exchange_mode', 'power_save_mode',
        'cts602_type', 'heatpump_typecode',
        'hidden_string.version_major', 'hidden_string.version_minor',
        'hidden_string.version_release',
        'firmware_version', 'bus_version',
        'hidden_number.alarm_count', 'alarm_generic.filter', 'alarm_pump_device',
        'hidden_number.co2_enable',
    ],
    1021: [
        'target_temperature', 'measure_temperature',
        'target_temperature.water', 'measure_temperature.water',
        'target_temperature.ek',
        'nl_target_humidity',
        'fan_speed.inlet1', 'fan_speed.inlet2', 'fan_speed.inlet3', 'fan_speed.inlet4',
        'fan_speed.exhaust1', 'fan_speed.exhaust2', 'fan_speed.exhaust3', 'fan_speed.exhaust4',
        'fan_mode.ventilation',
        'pump_mode.run', 'pump_mode.mode', 'pump_mode.air_exchange', 'pump_mode.power_save',
        'insights_number.compressor_state', 'insights_number.hot_water_state',
        'insights_number.externalheater',
        'insights_number.waterpump_state', 'insights_number.defrosting_state',
        'insights_number.electricheater', 'insights_number.ventilation',
        'insights_number.run_state',
        'insights_dec_number.T0_controller', 'insights_dec_number.T1_intake',
        'insights_dec_number.T2_inlet',
        'insights_dec_number.T5_cond', 'insights_dec_number.T6_evap',
        'insights_dec_number.T7_inlet',
        'insights_dec_number.T8_outdoor', 'insights_dec_number.T10_extern',
        'insights_dec_number.T11_water_top', 'insights_dec_number.T12_water_bottom',
        'insights_dec_number.T13_return', 'insights_dec_number.T14_supply',
        'insights_dec_number.T15_room', 'insights_dec_number.T16_aux',
        'insights_dec_number.central_heater_capacity',
        'insights_dec_number.compressor_capacity',
        'compressor_state',
        'electricheater',
        'externalheater',
        'hot_water_state',
        'waterpump_state',
        'defrosting_state',
        'measure_humidity',
        'measure_temperature.indoor', 'measure_temperature.outdoor',
        'measure_temperature.water_current',
        'measure_temperature.ek_supply', 'measure_temperature.ek_return',
        'measure_temperature.controller', 'measure_temperature.intake',
        'measure_temperature.inlet_before',
        'measure_temperature.cond', 'measure_temperature.evap',
        'measure_temperature.inlet_after',
        'measure_temperature.extern', 'measure_temperature.water_top',
        'measure_temperature.water_bottom',
        'measure_temperature.panel', 'measure_co2',
        'fanstep_enum.ventilation', 'fanstep.inlet', 'fanspeed.inlet', 'fanspeed.exhaust',
        'capacity.cenheat', 'capacity.compressor',
        'filter_days.left', 'filter_days.since',
        'run_state', 'heatpump_mode', 'heatpump_state', 'air_exchange_mode', 'power_save_mode',
        'cts602_type', 'heatpump_typecode',
        'hidden_string.version_major', 'hidden_string.version_minor',
        'hidden_string.version_release',
        'firmware_version', 'bus_version',
        'hidden_number.alarm_count', 'alarm_generic.filter', 'alarm_pump_device',
        'hidden_number.co2_enable',
    ],
}


def get_device_capabilities(devid: int = -1) -> List[str]:
    return DEVICE_CAPABILITIES.get(devid) or DEVICE_CAPABILITIES[-1]


def has_fw_caps(cap_ids: List[str]) -> bool:
    return (
        'bus_version' in cap_ids
        and 'hidden_string.version_major' in cap_ids
        and 'hidden_string.version_minor' in cap_ids
        and 'hidden_string.version_release' in cap_ids
        and 'firmware_version' in cap_ids
    )


def cap_is_fw_related(cap_id: str) -> bool:
    return cap_id in (
        'bus_version',
        'hidden_string.version_major',
        'hidden_string.version_minor',
        'hidden_string.version_release',
        'firmware_version',
    )


def cap_is_insights_number(cap_id: str) -> bool:
    return cap_id in (
        'insights_number.compressor_state',
        'insights_number.defrosting_state',
        'insights_number.electricheater',
        'insights_number.externalheater',
        'insights_number.hot_water_state',
        'insights_number.waterpump_state',
        'insights_number.run_state',
    )


def cap_is_alarm_related(cap_id: str) -> bool:
    return cap_id in (
        'hidden_number.alarm_count',
        'alarm_generic.filter',
        'alarm_pump_device',
    )
