"""Modbus register definitions for the Nilan CTS602 controller."""

from modbus_api import RegisterType

REGISTERS = {

    # ------------------------------------------------------------------ #
    # Input registers (read-only)                                         #
    # ------------------------------------------------------------------ #

    'Bus.Version': {
        'addr': 0,
        'type': RegisterType.Input,
        'description': 'Protocol version number',
    },
    'App.VersionMajor': {
        'addr': 1,
        'type': RegisterType.Input,
        'description': 'Software version - major (2 character ascii text)',
    },
    'App.VersionMinor': {
        'addr': 2,
        'type': RegisterType.Input,
        'description': 'Software version - minor (2 character ascii text)',
    },
    'App.VersionRelease': {
        'addr': 3,
        'type': RegisterType.Input,
        'description': 'Software version - release (2 character ascii text)',
    },
    'Input.AirFilter': {
        'addr': 101,
        'type': RegisterType.Input,
        'description': 'Air filter alarm',
    },
    'Input.T0_Controller': {
        'addr': 200,
        'type': RegisterType.Input,
        'description': 'Controller board temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T1_Intake': {
        'addr': 201,
        'type': RegisterType.Input,
        'description': 'Fresh air intake temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T2_Inlet': {
        'addr': 202,
        'type': RegisterType.Input,
        'description': 'Inlet temperature (before heater)',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T3_Exhaust': {
        'addr': 203,
        'type': RegisterType.Input,
        'description': 'Room exhaust temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T4_Outlet': {
        'addr': 204,
        'type': RegisterType.Input,
        'description': 'Outlet temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T5_Cond': {
        'addr': 205,
        'type': RegisterType.Input,
        'description': 'Condenser temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T6_Evap': {
        'addr': 206,
        'type': RegisterType.Input,
        'description': 'Evaporator temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T7_Inlet': {
        'addr': 207,
        'type': RegisterType.Input,
        'description': 'Inlet temperature (after heater)',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T8_Outdoor': {
        'addr': 208,
        'type': RegisterType.Input,
        'description': 'Outdoor temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T9_Heater': {
        'addr': 209,
        'type': RegisterType.Input,
        'description': 'Heating surface temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T10_Extern': {
        'addr': 210,
        'type': RegisterType.Input,
        'description': 'External room temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T11_Top': {
        'addr': 211,
        'type': RegisterType.Input,
        'description': 'Hot water top temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T12_Bottom': {
        'addr': 212,
        'type': RegisterType.Input,
        'description': 'Hot water bottom temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T13_Return': {
        'addr': 213,
        'type': RegisterType.Input,
        'description': 'EK return temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T14_Supply': {
        'addr': 214,
        'type': RegisterType.Input,
        'description': 'EK supply temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T15_Room': {
        'addr': 215,
        'type': RegisterType.Input,
        'description': 'User panel room temperature',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.T16': {
        'addr': 216,
        'type': RegisterType.Input,
        'description': 'AUX temperature (sacrificial anode)',
        'scale': 100,
        'min': -10000,
        'max': 10000,
    },
    'Input.RH': {
        'addr': 221,
        'type': RegisterType.Input,
        'description': 'Humidity',
        'scale': 100,
        'min': 0,
        'max': 10000,
    },
    'Input.CO2': {
        'addr': 222,
        'type': RegisterType.Input,
        'description': 'Carbon dioxide',
        'min': 0,
        'max': 40000,
    },
    'Alarm.Status': {
        'addr': 400,
        'type': RegisterType.Input,
        'description': 'Alarm state bit mask, 0x80 = Active, 0x03 = number of alarms',
    },
    'Alarm.List_1_ID': {
        'addr': 401,
        'type': RegisterType.Input,
        'description': 'Alarm 1 code',
    },
    'Alarm.List_2_ID': {
        'addr': 404,
        'type': RegisterType.Input,
        'description': 'Alarm 2 code',
    },
    'Alarm.List_3_ID': {
        'addr': 407,
        'type': RegisterType.Input,
        'description': 'Alarm 3 code',
    },
    'Control.RunAct': {
        'addr': 1000,
        'type': RegisterType.Input,
        'description': 'Actual on/off state',
        'min': 0,
        'max': 1,
    },
    'Control.ModeAct': {
        'addr': 1001,
        'type': RegisterType.Input,
        'description': 'Actual operation mode',
        'min': 0,
        'max': 4,
    },
    'Control.State': {
        'addr': 1002,
        'type': RegisterType.Input,
        'description': 'Actual control state',
        'min': 0,
        'max': 16,
    },
    'AirFlow.VentSet': {
        'addr': 1100,
        'type': RegisterType.Input,
        'description': 'Actual ventilation step set point',
    },
    'AirFlow.InletAct': {
        'addr': 1101,
        'type': RegisterType.Input,
        'description': 'Actual inlet fan speed step',
    },
    'AirFlow.ExhaustAct': {
        'addr': 1102,
        'type': RegisterType.Input,
        'description': 'Actual exhaust fan speed step',
    },
    'AirFlow.SinceFiltDay': {
        'addr': 1103,
        'type': RegisterType.Input,
        'description': 'Days since last air filter change alarm',
    },
    'AirFlow.ToFiltDay': {
        'addr': 1104,
        'type': RegisterType.Input,
        'description': 'Days to next air filter change alarm',
    },
    'AirTemp.IsSummer': {
        'addr': 1200,
        'type': RegisterType.Input,
        'description': 'Summer state',
        'min': 0,
        'max': 1,
    },
    'AirTemp.TempInlet': {
        'addr': 1201,
        'type': RegisterType.Input,
        'description': 'Inlet temperature request (T7 setpoint)',
        'scale': 100,
        'min': -5000,
        'max': 8000,
    },
    'AirTemp.TempControl': {
        'addr': 1202,
        'type': RegisterType.Input,
        'description': 'Actual value for controlled temperature',
        'scale': 100,
        'min': -5000,
        'max': 8000,
    },
    'AirTemp.TempRoom': {
        'addr': 1203,
        'type': RegisterType.Input,
        'description': 'Actual room temperature',
        'scale': 100,
        'min': -5000,
        'max': 8000,
    },
    'AirTemp.EffPct': {
        'addr': 1204,
        'type': RegisterType.Input,
        'description': 'Passive heat exchanger efficiency',
        'scale': 100,
        'min': -5000,
        'max': 8000,
    },
    'AirTemp.CapSet': {
        'addr': 1205,
        'type': RegisterType.Input,
        'description': 'Requested capacity',
        'scale': 100,
        'min': 0,
        'max': 10000,
    },
    'AirTemp.CapAct': {
        'addr': 1206,
        'type': RegisterType.Input,
        'description': 'Actual capacity',
        'scale': 100,
        'min': 0,
        'max': 10000,
    },
    'AirQual.CO2_Enable': {
        'addr': 3003,
        'type': RegisterType.Input,
        'description': 'Return > 0 if CO2 sensor is present, otherwise 0 or fail register reading',
    },

    # ------------------------------------------------------------------ #
    # Holding registers (read/write)                                      #
    # ------------------------------------------------------------------ #

    'Output.Compressor': {
        'addr': 109,
        'type': RegisterType.Holding,
        'description': 'Compressor',
        'min': 0,
        'max': 1,
    },
    'Output.WaterHeatEl': {
        'addr': 116,
        'type': RegisterType.Holding,
        'description': 'Electric hot water heating',
        'min': 0,
        'max': 1,
    },
    'Output.WaterHeat': {
        'addr': 117,
        'type': RegisterType.Holding,
        'description': 'Hot water heating',
        'min': 0,
        'max': 1,
    },
    'Output.CenCircPump': {
        'addr': 118,
        'type': RegisterType.Holding,
        'description': 'EK circulation pump',
        'min': 0,
        'max': 1,
    },
    'Output.CenHeat_1': {
        'addr': 119,
        'type': RegisterType.Holding,
        'description': 'EK heater relays 1',
        'min': 0,
        'max': 1,
    },
    'Output.CenHeat_2': {
        'addr': 120,
        'type': RegisterType.Holding,
        'description': 'EK heater relays 2',
        'min': 0,
        'max': 1,
    },
    'Output.CenHeat_3': {
        'addr': 121,
        'type': RegisterType.Holding,
        'description': 'EK heater relays 3',
        'min': 0,
        'max': 1,
    },
    'Output.CenHeatExt': {
        'addr': 122,
        'type': RegisterType.Holding,
        'description': 'External radiator heat',
        'min': 0,
        'max': 1,
    },
    'Output.Defrosting': {
        'addr': 125,
        'type': RegisterType.Holding,
        'description': 'Defrosting function active',
        'min': 0,
        'max': 1,
    },
    'Output.ExhaustSpeed': {
        'addr': 200,
        'type': RegisterType.Holding,
        'description': 'Exhaust fan speed',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Output.InletSpeed': {
        'addr': 201,
        'type': RegisterType.Holding,
        'description': 'Inlet fan speed',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Output.AirHeatCap': {
        'addr': 202,
        'type': RegisterType.Holding,
        'description': 'Air heater capacity',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Output.CenHeatCap': {
        'addr': 203,
        'type': RegisterType.Holding,
        'description': 'Central heater capacity',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Output.CprCap': {
        'addr': 204,
        'type': RegisterType.Holding,
        'description': 'Compressor capacity',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Output.EarthSpeed': {
        'addr': 205,
        'type': RegisterType.Holding,
        'description': 'Earth tube air intake fan speed',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Program.UserFuncAct': {
        'addr': 600,
        'type': RegisterType.Holding,
        'description': 'User function active',
        'min': 0,
        'max': 6,
    },
    'Program.UserFuncSet': {
        'addr': 601,
        'type': RegisterType.Holding,
        'description': 'User function select',
        'min': 0,
        'max': 6,
    },
    'Program.UserTimeSet': {
        'addr': 602,
        'type': RegisterType.Holding,
        'description': 'User function period',
        'min': 0,
        'max': 120,
    },
    'Control.Type': {
        'addr': 1000,
        'type': RegisterType.Holding,
        'description': 'Machine type select (DO NOT WRITE TO THIS)',
        'min': 0,
        'max': 255,
    },
    'Control.RunSet': {
        'addr': 1001,
        'type': RegisterType.Holding,
        'description': 'User on/off select',
        'min': 0,
        'max': 1,
    },
    'Control.ModeSet': {
        'addr': 1002,
        'type': RegisterType.Holding,
        'description': 'User operation mode select',
        'min': 0,
        'max': 4,
    },
    'Control.VentSet': {
        'addr': 1003,
        'type': RegisterType.Holding,
        'description': 'User ventilation step select',
        'min': 0,
        'max': 4,
    },
    'Control.TempSet': {
        'addr': 1004,
        'type': RegisterType.Holding,
        'description': 'User temperature setpoint',
        'scale': 100,
        'min': 500,
        'max': 3000,
    },
    'Control.ServiceMode': {
        'addr': 1005,
        'type': RegisterType.Holding,
        'description': 'Service mode select',
        'min': 0,
        'max': 8,
    },
    'Control.ServicePct': {
        'addr': 1006,
        'type': RegisterType.Holding,
        'description': 'Service mode capacity',
        'scale': 100,
        'min': 100,
        'max': 10000,
    },
    'Control.Preset': {
        'addr': 1007,
        'type': RegisterType.Holding,
        'description': 'Request preset to factory settings',
        'min': 0,
        'max': 3,
    },
    'AirFlow.AirExchMode': {
        'addr': 1100,
        'type': RegisterType.Holding,
        'description': 'Air exchange mode',
        'min': 0,
        'max': 2,
    },
    'HotWater.TempSet_T11': {
        'addr': 1700,
        'type': RegisterType.Holding,
        'description': 'Top temperature setpoint',
        'scale': 100,
        'min': 500,
        'max': 6500,
    },
    'HotWater.TempSet_T12': {
        'addr': 1701,
        'type': RegisterType.Holding,
        'description': 'Bottom temperature setpoint',
        'scale': 100,
        'min': 500,
        'max': 6500,
    },
    'CentralHeat.HeatExtern': {
        'addr': 1800,
        'type': RegisterType.Holding,
        'description': 'External heating offset from room temperature setpoint',
        'scale': 100,
        'min': 500,
        'max': 6500,
    },
    'CentralHeat.TempSet': {
        'addr': 1802,
        'type': RegisterType.Holding,
        'description': 'EK temperature setpoint',
        'scale': 100,
        'min': 500,
        'max': 6000,
    },
    'AirQual.RH_VentLo': {
        'addr': 1910,
        'type': RegisterType.Holding,
        'description': 'Humidity low winter step select',
    },
    'AirQual.RH_VentHi': {
        'addr': 1911,
        'type': RegisterType.Holding,
        'description': 'Humidity high step select',
    },
    'AirQual.RH_LimLo': {
        'addr': 1912,
        'type': RegisterType.Holding,
        'description': 'Humidity limit for low ventilation',
        'scale': 100,
        'min': 0,
        'max': 10000,
    },
    'AirQual.RH_Timeout': {
        'addr': 1913,
        'type': RegisterType.Holding,
        'description': 'Humidity max. time on high ventilation',
    },
    'Control.PowerSave': {
        'addr': 4041,
        'type': RegisterType.Holding,
        'description': 'Enable power saving features',
        'min': 0,
        'max': 1,
    },
    'AirFlow.InletSpd_1': {
        'addr': 4100,
        'type': RegisterType.Holding,
        'description': 'Inlet step 1 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.InletSpd_2': {
        'addr': 4101,
        'type': RegisterType.Holding,
        'description': 'Inlet step 2 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.InletSpd_3': {
        'addr': 4102,
        'type': RegisterType.Holding,
        'description': 'Inlet step 3 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.InletSpd_4': {
        'addr': 4103,
        'type': RegisterType.Holding,
        'description': 'Inlet step 4 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.ExhaustSpd_1': {
        'addr': 4104,
        'type': RegisterType.Holding,
        'description': 'Exhaust step 1 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.ExhaustSpd_2': {
        'addr': 4105,
        'type': RegisterType.Holding,
        'description': 'Exhaust step 2 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.ExhaustSpd_3': {
        'addr': 4106,
        'type': RegisterType.Holding,
        'description': 'Exhaust step 3 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
    'AirFlow.ExhaustSpd_4': {
        'addr': 4107,
        'type': RegisterType.Holding,
        'description': 'Exhaust step 4 speed setup (20-100)',
        'min': 20,
        'max': 100,
    },
}
